# frozen_string_literal: true

require 'solidus/permission_sets/base'
require 'solidus/permission_sets/configuration_display'
require 'solidus/permission_sets/configuration_management'
require 'solidus/permission_sets/dashboard_display'
require 'solidus/permission_sets/default_customer'
require 'solidus/permission_sets/order_display'
require 'solidus/permission_sets/order_management'
require 'solidus/permission_sets/product_display'
require 'solidus/permission_sets/product_management'
require 'solidus/permission_sets/promotion_display'
require 'solidus/permission_sets/promotion_management'
require 'solidus/permission_sets/restricted_stock_display'
require 'solidus/permission_sets/restricted_stock_management'
require 'solidus/permission_sets/stock_display'
require 'solidus/permission_sets/stock_management'
require 'solidus/permission_sets/super_user'
require 'solidus/permission_sets/user_display'
require 'solidus/permission_sets/user_management'
