eval(File.read(File.dirname(__FILE__) + '/../common_spree_dependencies.rb'))

gem 'solidus_core', path: '../core'
gem 'solidus_api', path: '../api'

gemspec

gem 'teaspoon', require: false
gem 'teaspoon-mocha', require: false
