require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rspec/core/rake_task'

require 'solidus_backend'
require 'spree/testing_support/dummy_app/rake_tasks'

ENV['LIB_NAME'] = 'solidus_backend'

RSpec::Core::RakeTask.new
task default: :spec

desc "Run the javascript specs"
task :teaspoon do
  require "teaspoon/console"

  options = {
    files: ENV["files"].nil? ? [] : ENV["files"].split(","),
    suite: ENV["suite"],
    coverage: ENV["coverage"],
    driver_options: ENV["driver_options"],
  }

  options.delete_if { |k, v| v.nil? }

  abort("rake teaspoon failed") if Teaspoon::Console.new(options).failures?
end

namespace :teaspoon do
  task :server  do
    require 'teaspoon'
    require 'spree/testing_support/dummy_app'
    require 'teaspoon/server'

    server = Teaspoon::Server.new
    server.start
    puts "#{server.url}/teaspoon"
    sleep
  end
end

task test_app: 'db:reset'
