version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.5.3
  codecov: codecov/codecov@3.3.0

executors:
  base:
    parameters: &parameters
      ruby:
        type: string
        default: "3.1"
    working_directory: &workdir ~/solidus
    environment: &environment
      DEFAULT_MAX_WAIT_TIME: 10
      SOLIDUS_RAISE_DEPRECATIONS: true
      CIRCLE_TEST_REPORTS: /tmp/test-results
      CIRCLE_ARTIFACTS: /tmp/test-artifacts
      BUNDLE_WITHOUT: "lint,release"
    docker:
      - image: &image cimg/ruby:<< parameters.ruby >>-browsers

  postgres:
    parameters: *parameters
    working_directory: *workdir
    environment:
      <<: *environment
      DB: postgresql
      DB_HOST: localhost
      DB_USERNAME: root
    docker:
      - image: *image
      - image: jhawthorn/circleci-postgres-fast
        environment:
          POSTGRES_USER: root

  mysql:
    parameters: *parameters
    working_directory: *workdir
    environment:
      <<: *environment
      DB: mysql
      DB_HOST: 127.0.0.1
      DB_USERNAME: root
    docker:
      - image: *image
      - image: cimg/mysql:5.7

  sqlite:
    parameters: *parameters
    working_directory: *workdir
    environment:
      <<: *environment
      DB: sqlite
    docker:
      - image: *image

commands:
  setup:
    steps:
      - checkout
      - run:
          name: "Lock dependencies"
          command: |
            sudo gem update --system
            gem install bundler -v"~> 2.3" --conservative
            bundle lock
            ruby -v > .ruby-version
      - restore_cache:
          keys:
            - solidus-gems-v4-{{checksum ".ruby-version"}}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - solidus-gems-v4-{{checksum ".ruby-version"}}-{{ .Branch }}
            - solidus-gems-v4-{{checksum ".ruby-version"}}-main
            - solidus-gems-v4-{{checksum ".ruby-version"}}

      - run: |
          bundle config set path 'vendor/bundle'
          bundle check || bundle install
          bundle clean

      - save_cache:
          key: solidus-gems-v4-{{checksum ".ruby-version"}}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - libvips

  test:
    steps:
      - run:
          name: "Run Admin Tests"
          command: ./bin/build-ci admin
      - run:
          name: "Run Api Tests"
          command: ./bin/build-ci api
      - run:
          name: "Run Backend Tests"
          command: ./bin/build-ci backend
      - run:
          name: "Run Backend JS Tests"
          command: ./bin/build-ci "backend JS"
      - run:
          name: "Run Core Tests"
          command: ./bin/build-ci core
      - run:
          name: "Run Sample Tests"
          command: ./bin/build-ci sample
      - run:
          name: "Run Legacy Promotion Tests"
          command: ./bin/build-ci legacy_promotions
      - run:
          name: "Run Friendly Promotion Tests"
          command: ./bin/build-ci promotions

      - store_artifacts:
          path: /tmp/test-artifacts
          destination: test-artifacts

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

  libvips:
    steps:
      - run:
          name: Fix APT mirrors
          command: |
            sudo sed -i 's|http://archive.ubuntu.com|http://ubuntu.cs.utah.edu|g' /etc/apt/sources.list
            sudo sed -i 's|http://security.ubuntu.com|http://ubuntu.cs.utah.edu|g' /etc/apt/sources.list
            sudo apt-get update
      - run:
          name: Install libvips
          command: |
            sudo apt-get install -y libvips-dev

jobs:
  test_solidus:
    parameters:
      database:
        type: string
        default: postgres
      ruby:
        type: string
        default: "3.2"
      rails:
        type: string
        default: "7.1"
      paperclip:
        type: boolean
        default: true
    executor:
      name: << parameters.database >>
      ruby: << parameters.ruby >>
    parallelism: 3
    environment:
      DISABLE_ACTIVE_STORAGE: << parameters.paperclip >>
      BUILDKITE_ANALYTICS_EXECUTION_NAME_PREFIX: "(<< parameters.ruby >>:<< parameters.rails >>:<< parameters.database >>:<< parameters.paperclip >>)"
    steps:
      - checkout
      - run:
          name: "Set the RAILS_VERSION environment variable"
          command: |
            # If << parameters.rails >> is a kown branch name, use the latest version of that branch
            # otherwise interpret it as a partial version number.
            RAILS_VERSION=$(echo "<< parameters.rails >>" | grep -qE "(stable|main)" && echo "~> << parameters.rails >>.0" || echo "<< parameters.rails >>")
            echo "RAILS_VERSION=$RAILS_VERSION" >> $BASH_ENV
            source $BASH_ENV
      - setup
      - test

  # This job creates a dir to hold coverage data, run test suites with coverage enabled and
  # generate the coverage report.
  test_solidus_with_coverage:
    parameters:
      database:
        type: string
        default: postgres
      ruby:
        type: string
        default: "3.2"
    executor:
      name: << parameters.database >>
      ruby: << parameters.ruby >>
    parallelism: 3
    environment:
      COVERAGE: "true"
      COVERAGE_DIR: /tmp/coverage
      DISABLE_ACTIVE_STORAGE: false
    steps:
      - setup
      - run:
          name: Setup Coverage Env Vars
          command: |
            echo 'export COVERAGE_FILE=/tmp/coverage/coverage.xml' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Verify Coverage Env Vars
          command: |
            echo $COVERAGE
            echo /tmp/coverage
            echo /tmp/coverage/coverage.xml
      - run:
          name: Setup Coverage Directory
          command: mkdir -p /tmp/coverage
      - test
      - run:
          name: Report Coverage
          command: bundle exec rake solidus:coverage[cobertura]
      - codecov/upload:
          file: /tmp/coverage/coverage.xml

workflows:
  build:
    jobs:
      - test_solidus_with_coverage # Only test with coverage support with the default versions

      # Based on supported versions for the current Solidus release and recommended versions from
      # https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html.
      - test_solidus:
          name: &name "test-rails-<<matrix.rails>>-ruby-<<matrix.ruby>>-<<matrix.database>>-<<#matrix.paperclip>>paperclip<</matrix.paperclip>><<^matrix.paperclip>>activestorage<</matrix.paperclip>>"
          matrix:
            {
              parameters:
                {
                  rails: ["7.0", "7.1", "7.2", "8.0"],
                  ruby: ["3.1"],
                  database: ["mysql"],
                  paperclip: [true],
                },
            }
      - test_solidus:
          name: *name
          matrix:
            {
              parameters:
                {
                  rails: ["7.0", "7.1", "7.2", "8.0"],
                  ruby: ["3.1"],
                  database: ["postgres"],
                  paperclip: [false],
                },
            }
      - test_solidus:
          name: *name
          matrix:
            {
              parameters:
                {
                  rails: ["7.1"],
                  ruby: ["3.2"],
                  database: ["sqlite"],
                  paperclip: [false],
                },
            }
      - test_solidus:
          name: *name
          matrix:
            {
              parameters:
                {
                  rails: ["7.2", "8.0", "main"],
                  ruby: ["3.3.5"],
                  database: ["sqlite"],
                  paperclip: [false],
                },
            }
      - test_solidus:
          name: *name
          matrix:
            {
              parameters:
                {
                  rails: ["7.2", "8.0"],
                  ruby: ["3.4.1"],
                  database: ["postgres"],
                  paperclip: [false],
                },
            }
