require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rspec/core/rake_task'
require 'spree/testing_support/common_rake'

ENV['LIB_NAME'] = 'solidus_core'

require 'standalone_migrations'

StandaloneMigrations::Tasks.load_tasks

RSpec::Core::RakeTask.new

task default: :spec

task :test_app do
  Rake::Task['db:create'].invoke
  Rake::Task['db:migrate'].invoke
end
