require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rspec/core/rake_task'
require 'spree/testing_support/dummy_app/rake_tasks'

RSpec::Core::RakeTask.new
task default: :spec

DummyApp::RakeTasks.new(
  gem_root: File.dirname(__FILE__),
  lib_name: 'solidus_core'
)

namespace :spec do
  task :isolated do
    Dir['spec/**/*_spec.rb'].all? do |file|
      sh('rspec', file)
    end || raise("Failures")
  end
end

task test_app: 'db:reset'
