# frozen_string_literal: true

require "rubygems"
require "rake"
require "rake/testtask"
require "rspec/core/rake_task"
require "solidus_i18n"
require "spree/testing_support/dummy_app/rake_tasks"
require "bundler/gem_tasks"

RSpec::Core::RakeTask.new
task default: :spec

DummyApp::RakeTasks.new(
  gem_root: File.dirname(__FILE__),
  lib_name: "solidus_i18n"
)

namespace :solidus_i18n do
  desc "Update by retrieving the latest Solidus locale files"
  task update_default: :environment do
    require "open-uri"
    puts "Fetching latest Solidus locale file"
    location = "https://raw.github.com/solidusio/solidus/main/core/config/locales/en.yml"

    File.write("#{locales_dir}/en.yml", URI.parse(location).read)
  end

  def locales_dir
    File.join File.dirname(__FILE__), "config/locales"
  end
end

task test_app: "db:reset"
