eval(File.read(File.dirname(__FILE__) + '/../common_spree_dependencies.rb'))
eval(File.read(File.dirname(__FILE__) + '/../common_rails_dependencies.rb'))

gem 'solidus_core', path: '../core'

gemspec
