# frozen_string_literal: true

require "solidus_friendly_promotions/testing_support/friendly_promotion_code_factory"
require "solidus_friendly_promotions/testing_support/friendly_promotion_category_factory"
require "solidus_friendly_promotions/testing_support/friendly_promotion_factory"

FactoryBot.define do
end
